// IT DEFINES HOW MANY TYPES OF ACTIONS TO BE PERFORMED IN THE WHOLE APP

export default {
    CREATE_DATA: 'CREATE_DATA',
    READ_DATA: 'READ_DATA',
    DELETE_DATA: 'DELETE_DATA',
    UPDATE_DATA: 'UPDATE_DATA',
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT'
}