// THIS FILE IS RESPONSIBLE FOR ALL THE STATE NAMES IN THE WHOLE PROJECT
export const CREATE_DATA = 'CREATE_DATA';
export const READ_DATA = 'READ_DATA';
export const DELETE_DATA = 'DELETE_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

// LOADER
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

// AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';



// ITEMS

export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_FAIL = 'CREATE_ITEM_FAIL';

export const GET_ITEMS_BY_CATEGORY_SUCCESS = 'GET_ITEMS_BY_CATEGORY_SUCCESS';
export const GET_ITEMS_BY_CATEGORY_FAIL = 'GET_ITEMS_BY_CATEGORY_FAIL';

export const GET_ALL_ITEMS_SUCCESS = 'GET_ALL_ITEMS_SUCCESS';
export const GET_ALL_ITEMS_FAIL = 'GET_ALL_ITEMS_FAIL';

export const GET_SINGLE_ITEM_SUCCESS = 'GET_SINGLE_ITEM_SUCCESS';
export const GET_SINGLE_ITEM_FAIL = 'GET_SINGLE_ITEM_FAIL';

export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL';

export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL';


// CART 
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_FAIL = 'ADD_CART_FAIL';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAIL = 'GET_CART_FAIL';